// miraculous-kingdom-frontend/src/app/rules/page.tsx
"use client";
import React, { useState, useEffect } from "react";
import { BsSearch } from "react-icons/bs";

import { Rule, RulesConst } from "./rules";
import { rule } from "postcss";


export default function Page() {

    const [ruleSearch, setRuleSearch] = useState("");
    const [rules, setRules] = useState([] as Rule[]);

    useEffect(() => {
        if (ruleSearch !== "") {
            const newRules: Rule[] = [];
            RulesConst.forEach((rule) => {
                let arr: String[] = rule.searchableName;
                let flag: boolean = false;
                let item: number = 0;
                while (!flag) {
                    flag = arr[item].match(ruleSearch) !== null;
                    ++item;
                    if (item >= arr.length) {
                        break;
                    }
                }
                if (flag) {
                    newRules.push(rule);
                }
            });
            if (newRules.length === 0) {
                setRules(RulesConst as any);
                return;
            }
            setRules(newRules as any);
        } else {
            setRules(RulesConst as any);
        }
    }, [ruleSearch]);


    return (
        <div className="flex max-h-fit flex-col items-center justify-center overflow-y-scroll">
            <div className="py-8 text-6xl text-red-700">Rules</div>
            <div className="mb-8 flex w-2/3 flex-row items-center justify-start rounded-full bg-slate-700 p-4 text-xl text-blue-500">
                <BsSearch className="mr-8" />
                <input
                    placeholder="Search for a topic."
                    className="w-11/12 bg-slate-700 outline-none"
                    value={ruleSearch}
                    onChange={(e) => setRuleSearch(e.currentTarget.value)}
                />
            </div>
            <div className="flex flex-col overflow-y-auto overflow-x-hidden text-center text-lg">
                {rules.sort((rule0, rule1) => {
                    return rule0.title.localeCompare(rule1.title);
                }).map((node) => {
                    return (
                        <div className="flex flex-col justify-center mx-8 mb-4 pb-8 text-xl rounded-xl bg-slate-500/50">
                            <div className="text-2xl text-blue-500">
                                {node.title}
                            </div>
                            {node.ele}
                        </div>
                    );
                })}
            </div>
        </div>
    );
}

// miraculous-kingdom/src/pages/rules/Rules.svelte
<script lang="ts">
    import { onMount } from 'svelte'
    import * as Components from '../../components'
    import { RulesConst, type Rule } from './rules'

    let search: string

    $: handledRules = [] as Rule[]

    onMount(() => {
        handledRules = RulesConst
    })

    const handleSearch = () => {
        if (search !== '') {
            const newRules: Rule[] = []
            RulesConst.forEach((rule) => {
                let arr: String[] = rule.searchableName
                let flag: boolean = false
                let item: number = 0
                while (!flag) {
                    flag = arr[item].match(search) !== null
                    ++item
                    if (item >= arr.length) {
                        break
                    }
                }
                if (flag) {
                    newRules.push(rule)
                }
            })
            if (newRules.length === 0) {
                handledRules = RulesConst
                return
            }
            handledRules = newRules
        } else {
           handledRules = RulesConst
        }
    }

    const handleClick = (link: string) => {
        window.location.href = link
    }
</script>

<Components.Wrapper title="Rules">
    <Components.Input
        value={search}
        placeholder="Search for a Rule"
        onChange={(_value) => {
            handleSearch()
        }}
        label="Search"
        inputType="text"
    />
    {#each handledRules as rule}
        <div class="group relative h-24 w-full my-8">
            <div
                class="absolute h-full w-full rounded bg-gradient-to-r from-fuchsia-600 to-blue-600 opacity-75 blur transition duration-150 ease-in-out group-hover:from-fuchsia-500 group-hover:to-blue-500 group-hover:opacity-90 group-hover:blur-lg"
            />
            <div
                on:click={() => handleClick(rule.link)}
                class="relative grid h-full w-full grid-cols-5 items-center divide-red-600 rounded-lg bg-slate-300 px-8 py-4 leading-none dark:bg-black"
            >
                <div class="text-red-600">{rule.title}</div>
                <div class="col-span-4">{rule.description}</div>
            </div>
        </div>
    {/each}
</Components.Wrapper>
