// miraculous-kingdom/src/pages/games/StartGame.svelte
<script lang="ts">
    import { ApiGameApiService, type GameCreation } from '../../models'
    import * as Components from '../../components'

    let name: string
    let ruler_name: string

    const onClick = () => {
        const request: GameCreation = {
            game_name: name,
            game_ruler: ruler_name,
            game_num_players: 0,
        }

        ApiGameApiService.startGame(request)
            .then((resp) => {
                window.location.href = `/games/create_character/${resp.data}`
            })
            .catch((err) => console.log(err))
    }
</script>

<div
    class="flex min-h-screen w-10/12 flex-col items-center rounded-xl bg-slate-600/70 px-12 pt-6 text-center align-top text-xl text-slate-300 backdrop-blur-lg"
>
    <div
        class="top-0 mb-8 w-full rounded-xl bg-slate-800 p-8 text-7xl font-bold text-blue-600"
    >
        Start Game
    </div>
    <div class="justify-content flex w-1/2 flex-col">
        <div class="place-items-start">
            <Components.Input
                inputType={null}
                placeholder="Tywin Lanister"
                value={name}
                onChange={(value) => {
                    name = value
                }}
                label={'Country Name'}
            />
            <Components.Input
                inputType={null}
                placeholder="Godrick The Grafted"
                value={ruler_name}
                onChange={(value) => {
                    ruler_name = value
                }}
                label={'Ruler'}
            />
        </div>
        <div class="mt-24 flex w-1/3 flex-row items-center align-middle">
            <Components.Button {onClick}>Create a Game</Components.Button>
        </div>
    </div>
</div>

// miraculous-kingdom-frontend/src/app/start/StartGame.tsx
"use client";

// external
import React, { useState, useEffect } from "react";

// internal
import { Models, Routes } from "../../index";

export default function StartGame(): JSX.Element {

    const [ create, setCreate ] = useState({
        game_name: "",
        game_ruler: "",
        game_num_players: 0
    } as Models.GameCreation);
    const [ ruler, setRuler ] = useState("");
    const [ country, setCountry ] = useState("");

    useEffect(() => {
        setCreate({
            game_num_players: 0,
            game_ruler: ruler,
            game_name: country
        } as Models.GameCreation) 
    }, [ruler, country])

    const handleSubmit = () => {
        console.log({"submitted": create});
    };

    return (
        <form 
            className="flex flex-col" 
            onSubmit={handleSubmit}
        >
            <label>
                Country Name 
                <input 
                    type="text"
                    value={country}
                    placeholder="Hamunaptra"
                    onChange={(e) => {
                        setCountry(e.currentTarget.value);
                    }}
                />
            </label>
            <label>
                Ruler Name 
                <input 
                    type="text"
                    value={ruler}
                    placeholder="Imohtep"
                    onChange={(e) => {
                        setRuler(e.currentTarget.value);
                    }}
                />
            </label>
            <button type="submit">
            </button>
        </form>
    );
}
